const builtin = @import("builtin");

pub usingnamespace switch (builtin.zig_backend) {
    .stage1 => @cImport({
        @cInclude("uv.h");
    }),

    // Workaround for:
    // https://github.com/ziglang/zig/issues/12325
    //
    // Generated by `udate_cimport.sh`
    else => switch (builtin.os.tag) {
        .linux => @import("cimport_linux.zig"),
        .macos => @import("cimport_macos.zig"),
        else => @compileError("unsupported OS for now, see this line"),
    },
};
